// <auto-generated />
using System;
using ChampionsLeague.Domains.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChampionsLeague.Domains.Migrations
{
    [DbContext(typeof(ChampionsLeagueDbContext))]
    [Migration("20260414121216_AddStartEindDatumToCompetitie")]
    partial class AddStartEindDatumToCompetitie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Abonnement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int")
                        .HasColumnName("club_id");

                    b.Property<int?>("Orderlineid")
                        .HasColumnType("int")
                        .HasColumnName("orderlineid");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prijs");

                    b.Property<int>("ZitplaatsId")
                        .HasColumnType("int")
                        .HasColumnName("zitplaats_id");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("Orderlineid");

                    b.HasIndex(new[] { "ZitplaatsId" }, "UQ__Abonneme__4ECF5B70B7B226DD")
                        .IsUnique();

                    b.ToTable("Abonnement", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("naam");

                    b.Property<int>("StadionId")
                        .HasColumnType("int")
                        .HasColumnName("stadion_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StadionId" }, "UQ__Club__3EC28F0C79C20726")
                        .IsUnique();

                    b.HasIndex(new[] { "Naam" }, "UQ__Club__72E1CD788D8247FA")
                        .IsUnique()
                        .HasFilter("[naam] IS NOT NULL");

                    b.ToTable("Club", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Competitie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EindDatum")
                        .HasColumnType("date");

                    b.Property<string>("Naam")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("naam");

                    b.Property<DateOnly?>("StartDatum")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Naam" }, "UQ__Competit__72E1CD78E8C69DBC")
                        .IsUnique()
                        .HasFilter("[naam] IS NOT NULL");

                    b.ToTable("Competitie", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BezoekersclubId")
                        .HasColumnType("int")
                        .HasColumnName("bezoekersclub_id");

                    b.Property<int>("CompetitieId")
                        .HasColumnType("int")
                        .HasColumnName("competitie_id");

                    b.Property<DateOnly?>("MatchDate")
                        .HasColumnType("date")
                        .HasColumnName("match_date");

                    b.Property<int>("StadionId")
                        .HasColumnType("int")
                        .HasColumnName("stadion_id");

                    b.Property<int>("ThuisclubId")
                        .HasColumnType("int")
                        .HasColumnName("thuisclub_id");

                    b.HasKey("Id");

                    b.HasIndex("BezoekersclubId");

                    b.HasIndex("CompetitieId");

                    b.HasIndex("StadionId");

                    b.HasIndex(new[] { "ThuisclubId", "BezoekersclubId", "MatchDate" }, "UQ_Match")
                        .IsUnique()
                        .HasFilter("[match_date] IS NOT NULL");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("order_date");

                    b.Property<decimal>("TotalePrijs")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("totale_prijs");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Orderline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prijs");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Orderline", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Stadion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capaciteit")
                        .HasColumnType("int")
                        .HasColumnName("capaciteit");

                    b.Property<string>("Naam")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("naam");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Naam" }, "UQ__Stadion__72E1CD78DAD7BB7D")
                        .IsUnique()
                        .HasFilter("[naam] IS NOT NULL");

                    b.ToTable("Stadion", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Stadionvak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capaciteit")
                        .HasColumnType("int")
                        .HasColumnName("capaciteit");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("naam");

                    b.Property<string>("Partij")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("partij");

                    b.Property<string>("Ring")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ring");

                    b.Property<int>("StadionId")
                        .HasColumnType("int")
                        .HasColumnName("stadion_id");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StadionId", "Ring", "Type", "Partij" }, "UQ_Stadionvak_Combinatie")
                        .IsUnique()
                        .HasFilter("[ring] IS NOT NULL AND [type] IS NOT NULL AND [partij] IS NOT NULL");

                    b.ToTable("Stadionvak", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int")
                        .HasColumnName("match_id");

                    b.Property<int?>("Orderlineid")
                        .HasColumnType("int")
                        .HasColumnName("orderlineid");

                    b.Property<decimal>("Prijs")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("prijs");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("ZitplaatsId")
                        .HasColumnType("int")
                        .HasColumnName("zitplaats_id");

                    b.HasKey("Id");

                    b.HasIndex("Orderlineid");

                    b.HasIndex("ZitplaatsId");

                    b.HasIndex(new[] { "MatchId", "ZitplaatsId" }, "UQ_Ticket_SeatMatch")
                        .IsUnique();

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("code");

                    b.Property<int>("TicketId")
                        .HasColumnType("int")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "UQ__Voucher__357D4CF96C9047AB")
                        .IsUnique();

                    b.HasIndex(new[] { "TicketId" }, "UQ__Voucher__D596F96AE34F7B2C")
                        .IsUnique();

                    b.ToTable("Voucher", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Zitplaats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StadionvakId")
                        .HasColumnType("int")
                        .HasColumnName("stadionvak_id");

                    b.Property<string>("ZitplaatsNummer")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ZitplaatsNummer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "StadionvakId", "ZitplaatsNummer" }, "UQ_Zitplaats_VakNummer")
                        .IsUnique()
                        .HasFilter("[ZitplaatsNummer] IS NOT NULL");

                    b.ToTable("Zitplaats", (string)null);
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Abonnement", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Club", "Club")
                        .WithMany("Abonnements")
                        .HasForeignKey("ClubId")
                        .IsRequired()
                        .HasConstraintName("FK_Abonnement_Club");

                    b.HasOne("ChampionsLeague.Domains.Entities.Orderline", "Orderline")
                        .WithMany("Abonnements")
                        .HasForeignKey("Orderlineid")
                        .HasConstraintName("FK_Abonnement_Orderline");

                    b.HasOne("ChampionsLeague.Domains.Entities.Zitplaats", "Zitplaats")
                        .WithOne("Abonnement")
                        .HasForeignKey("ChampionsLeague.Domains.Entities.Abonnement", "ZitplaatsId")
                        .IsRequired()
                        .HasConstraintName("FK_Abonnement_Zitplaats");

                    b.Navigation("Club");

                    b.Navigation("Orderline");

                    b.Navigation("Zitplaats");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Club", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Stadion", "Stadion")
                        .WithOne("Club")
                        .HasForeignKey("ChampionsLeague.Domains.Entities.Club", "StadionId")
                        .IsRequired()
                        .HasConstraintName("FK_Club_Stadion");

                    b.Navigation("Stadion");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Match", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Club", "Bezoekersclub")
                        .WithMany("MatchBezoekersclubs")
                        .HasForeignKey("BezoekersclubId")
                        .IsRequired()
                        .HasConstraintName("FK_Match_Bezoekersclub");

                    b.HasOne("ChampionsLeague.Domains.Entities.Competitie", "Competitie")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitieId")
                        .IsRequired()
                        .HasConstraintName("FK_Match_Competitie");

                    b.HasOne("ChampionsLeague.Domains.Entities.Stadion", "Stadion")
                        .WithMany("Matches")
                        .HasForeignKey("StadionId")
                        .IsRequired()
                        .HasConstraintName("FK_Match_Stadion");

                    b.HasOne("ChampionsLeague.Domains.Entities.Club", "Thuisclub")
                        .WithMany("MatchThuisclubs")
                        .HasForeignKey("ThuisclubId")
                        .IsRequired()
                        .HasConstraintName("FK_Match_Thuisclub");

                    b.Navigation("Bezoekersclub");

                    b.Navigation("Competitie");

                    b.Navigation("Stadion");

                    b.Navigation("Thuisclub");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Order", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_AspNetUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Orderline", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Order", "Order")
                        .WithMany("Orderlines")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_Orderline_Order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Stadionvak", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Stadion", "Stadion")
                        .WithMany("Stadionvaks")
                        .HasForeignKey("StadionId")
                        .IsRequired()
                        .HasConstraintName("FK_Stadionvak_Stadion");

                    b.Navigation("Stadion");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Ticket", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Match", "Match")
                        .WithMany("Tickets")
                        .HasForeignKey("MatchId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Match");

                    b.HasOne("ChampionsLeague.Domains.Entities.Orderline", "Orderline")
                        .WithMany("Tickets")
                        .HasForeignKey("Orderlineid")
                        .HasConstraintName("FK_Ticket_Orderline");

                    b.HasOne("ChampionsLeague.Domains.Entities.Zitplaats", "Zitplaats")
                        .WithMany("Tickets")
                        .HasForeignKey("ZitplaatsId")
                        .IsRequired()
                        .HasConstraintName("FK_Ticket_Zitplaats");

                    b.Navigation("Match");

                    b.Navigation("Orderline");

                    b.Navigation("Zitplaats");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Voucher", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Ticket", "Ticket")
                        .WithOne("Voucher")
                        .HasForeignKey("ChampionsLeague.Domains.Entities.Voucher", "TicketId")
                        .IsRequired()
                        .HasConstraintName("FK_Voucher_Ticket");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Zitplaats", b =>
                {
                    b.HasOne("ChampionsLeague.Domains.Entities.Stadionvak", "Stadionvak")
                        .WithMany("Zitplaats")
                        .HasForeignKey("StadionvakId")
                        .IsRequired()
                        .HasConstraintName("FK_Zitplaats_Stadionvak");

                    b.Navigation("Stadionvak");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Club", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("MatchBezoekersclubs");

                    b.Navigation("MatchThuisclubs");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Competitie", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Match", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Order", b =>
                {
                    b.Navigation("Orderlines");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Orderline", b =>
                {
                    b.Navigation("Abonnements");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Stadion", b =>
                {
                    b.Navigation("Club");

                    b.Navigation("Matches");

                    b.Navigation("Stadionvaks");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Stadionvak", b =>
                {
                    b.Navigation("Zitplaats");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Ticket", b =>
                {
                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("ChampionsLeague.Domains.Entities.Zitplaats", b =>
                {
                    b.Navigation("Abonnement");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
